### PR TITLE
Updated and added brightness

### PR DESCRIPTION
**Pull request by daniilfigasystems**

### CODE REVIEW

**Review by daniilfigasystems — COMMENTED** [review]
wrong

**Comment by devos50** [comment]
Thank you for your contribution! I'm looking at your code and testing it, but somehow commit https://github.com/devos50/qemu-ios/pull/202/commits/2f56460a8593fd8ed8279100e534390201436d03 isn't in the global overview?

Anyway, I'm getting the same error about the `void *` type when compiling so I'll try to fix it directly!

**Comment by devos50** [comment]
Are you actually able to compile the project? I'm getting a bunch of errors:

```
(base) martijndevos@iMacvanMartijn build % make
  GIT     ui/keycodemapdb meson tests/fp/berkeley-testfloat-3 tests/fp/berkeley-softfloat-3 dtc
[1/498] Generating qemu-version.h with a custom command (wrapped by meson to capture output)
[2/498] Compiling C object libqmp.fa.p/monitor_qmp-cmds-control.c.o
[3/498] Linking static target libqmp.fa
[4/498] Compiling Objective-C object libcommon.fa.p/ui_cocoa.m.o
[5/498] Compiling C object libcommon.fa.p/softmmu_vl.c.o
[6/498] Compiling C object libqemu-arm-softmmu.fa.p/hw_arm_ipod_touch_2g.c.o
FAILED: libqemu-arm-softmmu.fa.p/hw_arm_ipod_touch_2g.c.o 
cc -m64 -mcx16 -Ilibqemu-arm-softmmu.fa.p -I. -I.. -Itarget/arm -I../target/arm -I../dtc/libfdt -Iqapi -Itrace -Iui -Iui/shader -I/usr/local/Cellar/pixman/0.44.2/include/pixman-1 -I/usr/local/opt/openssl@3/include -I/usr/local/Cellar/glib/2.82.4/include -I/usr/local/Cellar/glib/2.82.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.82.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre2/10.44/include -fcolor-diagnostics -Wall -Winvalid-pch -std=gnu11 -O2 -g -iquote . -iquote /Users/martijndevos/Documents/qemu-it2g -iquote /Users/martijndevos/Documents/qemu-it2g/include -iquote /Users/martijndevos/Documents/qemu-it2g/tcg/i386 -DOS_OBJECT_USE_OBJC=0 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wno-initializer-overrides -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-string-plus-int -Wno-typedef-redefinition -Wno-tautological-type-limit-compare -Wno-psabi -Wno-gnu-variable-sized-type-not-at-end -fstack-protector-strong -DNEED_CPU_H '-DCONFIG_TARGET="arm-softmmu-config-target.h"' '-DCONFIG_DEVICES="arm-softmmu-config-devices.h"' -MD -MQ libqemu-arm-softmmu.fa.p/hw_arm_ipod_touch_2g.c.o -MF libqemu-arm-softmmu.fa.p/hw_arm_ipod_touch_2g.c.o.d -o libqemu-arm-softmmu.fa.p/hw_arm_ipod_touch_2g.c.o -c ../hw/arm/ipod_touch_2g.c
../hw/arm/ipod_touch_2g.c:62:5: error: incompatible function pointer types initializing 'CPReadFn *' (aka 'unsigned long long (*)(struct CPUArchState *, const struct ARMCPRegInfo *)') with an expression of type 'uint32_t (CPUARMState *)' (aka 'unsigned int (struct CPUArchState *)') [-Wincompatible-function-pointer-types]
   62 |     IT2G_CPREG_DEF_QEMU_CALL,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
../hw/arm/ipod_touch_2g.c:44:19: note: expanded from macro 'IT2G_CPREG_DEF_QEMU_CALL'
   44 |         .readfn = qemu_call_status, \
      |                   ^~~~~~~~~~~~~~~~
../hw/arm/ipod_touch_2g.c:62:5: error: incompatible function pointer types initializing 'CPWriteFn *' (aka 'void (*)(struct CPUArchState *, const struct ARMCPRegInfo *, unsigned long long)') with an expression of type 'void (CPUARMState *, uint32_t)' (aka 'void (struct CPUArchState *, unsigned int)') [-Wincompatible-function-pointer-types]
   62 |     IT2G_CPREG_DEF_QEMU_CALL,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
../hw/arm/ipod_touch_2g.c:45:20: note: expanded from macro 'IT2G_CPREG_DEF_QEMU_CALL'
   45 |         .writefn = qemu_call,     \
      |                    ^~~~~~~~~
../hw/arm/ipod_touch_2g.c:246:42: warning: passing 'const char[5]' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  246 |     DeviceState *dev = pl192_manual_init("vic0", qdev_get_gpio_in(DEVICE(nms->cpu), ARM_CPU_IRQ), qdev_get_gpio_in(DEVICE(nms->cpu), ARM_CPU_FIQ), NULL);
      |                                          ^~~~~~
/Users/martijndevos/Documents/qemu-it2g/include/hw/intc/pl192.h:78:38: note: passing argument to parameter 'mem_name' here
   78 | DeviceState *pl192_manual_init(char *mem_name, ...);
      |                                      ^
../hw/arm/ipod_touch_2g.c:253:29: warning: passing 'const char[5]' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  253 |     dev = pl192_manual_init("vic1", NULL);
      |                             ^~~~~~
/Users/martijndevos/Documents/qemu-it2g/include/hw/intc/pl192.h:78:38: note: passing argument to parameter 'mem_name' here
   78 | DeviceState *pl192_manual_init(char *mem_name, ...);
      |                                      ^
../hw/arm/ipod_touch_2g.c:424:16: warning: unused variable 'pmu' [-Wunused-variable]
  424 |     I2CSlave * pmu = i2c_slave_create_simple(i2c_state->bus, "pcf50633", 0x73);
      |                ^~~
../hw/arm/ipod_touch_2g.c:427:15: warning: unused variable 'accelerometer' [-Wunused-variable]
  427 |     I2CSlave *accelerometer = i2c_slave_create_simple(i2c_state->bus, "lis302dl", 0x1D);
      |               ^~~~~~~~~~~~~
../hw/arm/ipod_touch_2g.c:440:15: warning: unused variable 'cd327mikey' [-Wunused-variable]
  440 |     I2CSlave *cd327mikey = i2c_slave_create_simple(i2c_state->bus, "cd3272mikey", 0x39);
      |               ^~~~~~~~~~
5 warnings and 2 errors generated.
ninja: build stopped: subcommand failed.
make: *** [run-ninja] Error 1
```

I'll make a separate issue for this.

**Comment by daniilfigasystems** [comment]
So weird. I didn't actually changed ipod_touch_2g.c and i can compile it. I will review my code again.

**Comment by devos50** [comment]
Ah, it's probably a rebase issue. Rebasing your PR on the latest commit in the `ipod_touch_2g` branch should fix it 👍 .

**Comment by daniilfigasystems** [comment]
I think you can directly download from my repo and try to compile it.

**Comment by devos50** [comment]
Scherm­afbeelding 2024-12-22 om 11 18 56
Scherm­afbeelding 2024-12-22 om 11 18 49

This is so cool, thanks for your contribution!! 🎉 

If you cleanup your PR, I will merge it. Feel free to squash everything into a single commit 👍

**Comment by daniilfigasystems** [comment]
> If you cleanup your PR, I will merge it. Feel free to squash everything into a single commit 👍

Thanks. Unfortunately at this time my git bugged and i had to separate one commit to three small.

**Comment by daniilfigasystems** [comment]
Now i am working on NAND write.

**Comment by devos50** [comment]
NAND write would be amazing to have!

I can also fixup your PR if you want?

**Comment by daniilfigasystems** [comment]
> I can also fixup your PR if you want?

Sure.

**Comment by devos50** [comment]
@daniilfigasystems I just merged your changes! I also took the opportunity to disable some (very verbose) debugging stuff and disabled the WIFI driver by default, since it's quite unstable ATM.

If you have any questions regarding the NAND writes, please let me know!

**Comment by daniilfigasystems** [comment]
> @daniilfigasystems I just merged your changes! I also took the opportunity to disable some (very verbose) debugging stuff and disabled the WIFI driver by default, since it's quite unstable ATM.
> 
> If you have any questions regarding the NAND writes, please let me know!

Thanks! I have questions, look at issues.

**Pull request closed without merging**
