### PR TITLE
Fixed bugs added new devices

### PR DESCRIPTION
**Pull request by daniilfigasystems**
Fixed unexpected CLCD interrupt (for now only unexcepted interrupt from multitouch), added audio codec skeleton, added light sensor, fixed pressing other buttons lead to crash, added kernel patch check (improves perfomance a little), added more verbosity, planning to add working wifi (need datasheet)

### CODE REVIEW

**Comment by devos50** [comment]
Great work, thank you for your contribution! Please let me know when this PR is ready so I can review/merge it 👍

**Comment by daniilfigasystems** [comment]
> Great work, thank you for your contribution! Please let me know when this PR is ready so I can review/merge it 👍

Sure. I think I will format my code and find other bugs

**Comment by daniilfigasystems** [comment]
It’s ready to merge. If I find bugs I will open pr.

**Review by devos50 — APPROVED** [review]
Thank you!

**Pull request merged**
